### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by JarDv** [preboot/angularjs-webpack#102]
Hi.

I have a clean repository clone and on npm start command i get this message on browser:

![image](https://user-images.githubusercontent.com/4742036/41170119-486137da-6b08-11e8-86c9-0887f987915e.png)

**Comment by rickjjones** [comment]
I get the same.

**Comment by phra** [comment]
@JarDv @rickjjones I don't have time now to debug an AngularJS boilerplate.. you should really consider to move on Angular 6+ with the [official CLI](https://github.com/angular/angular-cli).

**Comment by erichbehrens** [comment]
@JarDv @rickjjones I had it working by changing line 48 of `webpack.config.js` from this:

 `publicPath: isProd ? '/' : 'http://0.0.0.0:8080/',`

to

`publicPath: '/'`

**Comment by phra** [comment]
@erichbehrens can you eventually send a PR? thanks.
