### ISSUE TITLE
Typo in webpack.config.js comment

### ISSUE THREAD

**Issue by mopsik** [preboot/angularjs-webpack#75]
Hello.
It seems that there's a typo in comment regarding istanbul loader.

I mean this line:

> //Skips node_modules and files that end with .test

While it actually seems to skip node_modules and files that end with .spec

**Comment by escapedcat** [comment]
https://github.com/preboot/angularjs-webpack/blob/master/webpack.config.js#L133
Providing direct link for easier access.

**Comment by phra** [comment]
@mopsik @escapedcat fixed, thanks.
