### ISSUE TITLE
When to use `templateUrl` vs `template: require('./app.html')`?

### ISSUE THREAD

**Issue by ugultopu** [preboot/angularjs-webpack#89]
In [app.js](https://github.com/preboot/angularjs-webpack/blob/master/src/app/app.js), the template is referenced as follows:

    template: require('./app.html')

However, AngularJS has a `templateUrl` option as well and it could have been written as following as well:

    templateUrl: './app.html'

What would be the differences between these two approaches?

**Comment by phra** [comment]
i think there were differences in the past. right now the suggested way is to use the `@angular/cli`. have a look [here](https://github.com/angular/angular-cli).
