### ISSUE TITLE
nothing show after first fresh build

### ISSUE THREAD

**Issue by ggktm** [preboot/angularjs-webpack#90]
I've just clone this first and installed all modules via `yarn install`

It succeeded if running at `yarn server`, it was nothing to modify the files there.
but when trying `yarn run build` at project root, the compile was success but it shows nothing and `net::ERR_FILE_NOT_FOUND` happens at console log.

The error begins while the compile progress shows the `DedupePlugin` warn to be removed. and `NoErrorsPlugin` was deprecated.

I'm waiting for the little fix here. thx in adv b4

Using latest Node.js (9.2.1), Windows 10 x64

**Comment by ggktm** [comment]
I've just clone this first and installed all modules via `yarn install`

It succeeded if running at `yarn server`, it was nothing to modify the files there.
but when trying `yarn run build` at project root, the compile was success but it shows nothing and `net::ERR_FILE_NOT_FOUND` happens at console log.

I'm waiting for the little fix here. thx in adv b4

**Comment by phra** [comment]
> I'm waiting for the little fix here. thx in adv b4

i'm no longer working on angular 1 projects.. maybe you can send a PR to fix the problem.

**Comment by damien-mcmahon** [comment]
I had the same issue with `app.bundle.js` not being found.

I changed the `webpack.config.js` file to reference `http://0.0.0.0:8080/` instead of `http://localhost:8080/` to get it displaying correctly in Chrome (on macOS). 

I've not bothered to understand why (and not tested other browsers) as this is just for a quick demo.

**Comment by damien-mcmahon** [comment]
PR is here:
https://github.com/preboot/angularjs-webpack/pull/92
