### ISSUE TITLE
ngMock function in global scope (module, inject, ...)

### ISSUE THREAD

**Issue by Mic75** [preboot/angularjs-webpack#96]
Hi there,

Thanks for this boilerplate, very handful.
Do you know why the functions from `ngMock` are not available in the global scope of the spec file ?

For example, if I replace, `angular.mock.module('app');`  by `module('app')` (in app.spec.js:9), I am having an error saying that `module` is undefined.

AngularJS doc say that [the function is published on windows for easy access](https://docs.angularjs.org/api/ngMock/function/angular.mock.module), but it looks like something is going wrong when using when using karma+webpack.

**Comment by phra** [comment]
i'm quite sure that webpack is preventing it to patching `window` object. just use `angular.mock.module()` instead.

**Comment by Mic75** [comment]
Thanks for the answer. Not quite correct though, since all jasmine function are available on window (`expect`, `spyOn`, ...). It looks like jasmine manage to patch window but not angular. Maybe something related to the order webpack is loading modules...

**Comment by phra** [comment]
yeah, i explained myself badly, probably the angular package is published with a [UMD](https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js) template so if you use a commonjs-like environment, like webpack, the package doesn't register itself on window.
